### ISSUE TITLE
CompositionalLotkaVolterra(P, T, U, pseudo_count=1e-5)

### ISSUE THREAD

**Issue by gaofengjie-2019** [tyjo/clv#2]
Dr.Tyler,
Sorry to bother you. Here I found a error when I run the function:
CompositionalLotkaVolterra(P, T, U, pseudo_count=1e-5)
That is:
clv = CompositionalLotkaVolterra(P, T, U, pseudo_count=1e-5)
Error: no valid denominator found
Traceback (most recent call last):

  File "<ipython-input-54-f5a56d6426c1>", line 1, in <module>
    clv = CompositionalLotkaVolterra(P, T, U, pseudo_count=1e-5)

  File "D:\pydata\clv\compositional_lotka_volterra.py", line 104, in __init__
    self.denom = choose_denom(P)

  File "D:\pydata\clv\compositional_lotka_volterra.py", line 62, in choose_denom
    exit(1)

NameError: name 'exit' is not defined

It indicates no valid denominator found. Maybe there are some problems in data from P or Y?The concentrations of each taxa in Y are the relative abundance, is it OK?
Fengjie

**Comment by tyjo** [comment]
What dataset are you running this on? What value are you using for the pseudo count?

Since cLV works under the additive log-ratio transformation, the code tries to make a sensible choice for the denomination. Specifically, it looks for a taxon present in all samples where the variance of the log change over time is small.

Since the denominator choice procedure requires taking a log, I suspect there might be zeros in the relative abundances (P).

**Comment by gaofengjie-2019** [comment]
> What dataset are you running this on? What value are you using for the pseudo count?
> 
> Since cLV works under the additive log-ratio transformation, the code tries to make a sensible choice for the denomination. Specifically, it looks for a taxon present in all samples where the variance of the log change over time is small.
> 
> Since the denominator choice procedure requires taking a log, I suspect there might be zeros in the relative abundances (P).

Thanks a lot for your reply. I have solved this problem.
